### ISSUE TITLE
Difficulty in installing the package through brew

### ISSUE THREAD

**Issue by mikeaalv** [gmrandazzo/libscientific#5]
I first try the brew option. 

```
% brew install --HEAD libscientific


Running `brew update --auto-update`...


^[[B==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Downloading https://formulae.brew.sh/api/formula.jws.json
###################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
###################################################################################################################### 100.0%
Warning: No available formula with the name "libscientific". Did you mean libident?
==> Searching for similarly named formulae and casks...
==> Formulae
libident

To install libident, run:
  brew install libident
```

The local installation from source seems fine. I have to modify a bit. The one-line command doesn't work for me but separating into multiple lines works. It can also be good that to mention the location the command should be run and a simple test on whether the installation is successful.

**Comment by jbytecode** [comment]
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/5420

**Comment by gmrandazzo** [comment]
Thank you! Fixed with this new release.

Unfortunately, the formula has not yet been submitted to homebrew officially, so it was not working. Hence you need first to tap this third part repository.

brew tap gmrandazzo/homebrew-gmr

And after installing the software, which will now also install the python library.

brew tap gmrandazzo/homebrew-gmr

I will comment this into the JOSS submission along with all the modifications I did to fix the issues!

**Comment by mikeaalv** [comment]
It can seems I can install it by the new guideline. I assume your second command is `brew install --HEAD libscientific`
